export enum URLEnum {
    BASE='/',
    HOME='/home',
    LOGIN='/login',
    DASHBOARD='/dashboard',
    SETTINGS='/settings',
    PROFILE='/profile',
    USERS='/users',
    CENTERS='/centers',
    DEMANDS='/demands',
    DEMANDS_ADD='/demands/add',
    TRANSPORTS='/transports',
    FOOD='/food',
    FOOD_ADD='/food/add',
    DISTRIBUTION_POINT='/distribution-points',
    DISTRIBUTION_POINT_ADD='/distribution-points/add',
    INVENTORY='/inventories',
    INVENTORY_ADD='/inventories/add'
} 